spring:
  graphql:
    schema:
      introspection:
        enabled: true
      printer:
        enabled: true
    graphiql:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

jwt:
  secret: ${JWT_SECRET}
  expiredDays: ${JWT_EXPIRED_DAYS}

kakao:
  clientId: ${KAKAO_CLIENT_ID}
  redirectUri: ${KAKAO_REDIRECT_URI}

s3:
  endpoint: ${S3_ENDPOINT}
  region: ${S3_REGION}
  credentialsAccessKey: ${S3_CREDENTIALS_ACCESS_KEY}
  credentialsSecretKey: ${S3_CREDENTIALS_SECRET_KEY}
  bucket: ${S3_BUCKET}
  domain: ${S3_DOMAIN}

context:
  initializer:
    classes: com.santaclose.app.config.BeansInitializer
