spring:
  graphql:
    schema:
      introspection:
        enabled: true
      printer:
        enabled: true
    graphiql:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

jwt:
  secret: "Xn2r5u8x/A?D*G-KaPdSgVkYp3s6v9y$"
  expiredDays: 30

kakao:
  clientId: ${KAKAO_CLIENT_ID:"clientId"}
  redirectUri: "http://localhost:8080/oauth"

s3:
  endpoint: "http://localhost:4568"
  region: "ap-northeast-2"
  credentialsAccessKey: "accesskey"
  credentialsSecretKey: "secretKey"
  bucket: "bucket"
  domain: "domain"

context:
  initializer:
    classes: com.santaclose.app.config.BeansInitializer
